# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import echo_pb.echo_pb2 as echo__pb2


class ECHOStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Square = channel.unary_unary(
                '/echo.ECHO/Square',
                request_serializer=echo__pb2.Message.SerializeToString,
                response_deserializer=echo__pb2.Message.FromString,
                )
        self.RangeSquare = channel.unary_stream(
                '/echo.ECHO/RangeSquare',
                request_serializer=echo__pb2.Message.SerializeToString,
                response_deserializer=echo__pb2.Message.FromString,
                )
        self.SumSquare = channel.stream_unary(
                '/echo.ECHO/SumSquare',
                request_serializer=echo__pb2.Message.SerializeToString,
                response_deserializer=echo__pb2.Message.FromString,
                )
        self.StreamrangeSquare = channel.stream_stream(
                '/echo.ECHO/StreamrangeSquare',
                request_serializer=echo__pb2.Message.SerializeToString,
                response_deserializer=echo__pb2.Message.FromString,
                )


class ECHOServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Square(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RangeSquare(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SumSquare(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamrangeSquare(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ECHOServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Square': grpc.unary_unary_rpc_method_handler(
                    servicer.Square,
                    request_deserializer=echo__pb2.Message.FromString,
                    response_serializer=echo__pb2.Message.SerializeToString,
            ),
            'RangeSquare': grpc.unary_stream_rpc_method_handler(
                    servicer.RangeSquare,
                    request_deserializer=echo__pb2.Message.FromString,
                    response_serializer=echo__pb2.Message.SerializeToString,
            ),
            'SumSquare': grpc.stream_unary_rpc_method_handler(
                    servicer.SumSquare,
                    request_deserializer=echo__pb2.Message.FromString,
                    response_serializer=echo__pb2.Message.SerializeToString,
            ),
            'StreamrangeSquare': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamrangeSquare,
                    request_deserializer=echo__pb2.Message.FromString,
                    response_serializer=echo__pb2.Message.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'echo.ECHO', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ECHO(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Square(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/echo.ECHO/Square',
            echo__pb2.Message.SerializeToString,
            echo__pb2.Message.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RangeSquare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/echo.ECHO/RangeSquare',
            echo__pb2.Message.SerializeToString,
            echo__pb2.Message.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SumSquare(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/echo.ECHO/SumSquare',
            echo__pb2.Message.SerializeToString,
            echo__pb2.Message.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamrangeSquare(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/echo.ECHO/StreamrangeSquare',
            echo__pb2.Message.SerializeToString,
            echo__pb2.Message.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
