# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: echo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='echo.proto',
  package='echo',
  syntax='proto3',
  serialized_options=b'Z\t./echo_pb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\necho.proto\x12\x04\x65\x63ho\"\x1a\n\x07Message\x12\x0f\n\x07Message\x18\x01 \x01(\x01\x32\xc9\x01\n\x04\x45\x43HO\x12(\n\x06Square\x12\r.echo.Message\x1a\r.echo.Message\"\x00\x12/\n\x0bRangeSquare\x12\r.echo.Message\x1a\r.echo.Message\"\x00\x30\x01\x12-\n\tSumSquare\x12\r.echo.Message\x1a\r.echo.Message\"\x00(\x01\x12\x37\n\x11StreamrangeSquare\x12\r.echo.Message\x1a\r.echo.Message\"\x00(\x01\x30\x01\x42\x0bZ\t./echo_pbb\x06proto3'
)




_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='echo.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Message', full_name='echo.Message.Message', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=46,
)

DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'echo_pb2'
  # @@protoc_insertion_point(class_scope:echo.Message)
  })
_sym_db.RegisterMessage(Message)


DESCRIPTOR._options = None

_ECHO = _descriptor.ServiceDescriptor(
  name='ECHO',
  full_name='echo.ECHO',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=49,
  serialized_end=250,
  methods=[
  _descriptor.MethodDescriptor(
    name='Square',
    full_name='echo.ECHO.Square',
    index=0,
    containing_service=None,
    input_type=_MESSAGE,
    output_type=_MESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RangeSquare',
    full_name='echo.ECHO.RangeSquare',
    index=1,
    containing_service=None,
    input_type=_MESSAGE,
    output_type=_MESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SumSquare',
    full_name='echo.ECHO.SumSquare',
    index=2,
    containing_service=None,
    input_type=_MESSAGE,
    output_type=_MESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StreamrangeSquare',
    full_name='echo.ECHO.StreamrangeSquare',
    index=3,
    containing_service=None,
    input_type=_MESSAGE,
    output_type=_MESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ECHO)

DESCRIPTOR.services_by_name['ECHO'] = _ECHO

# @@protoc_insertion_point(module_scope)
